vm_name = "alpine-vm01"

Vagrant.configure("2") do |config|
  config.vm.box = "alpine/alpine64"
  config.vm.hostname = "#{vm_name}"
  config.vm.define "#{vm_name}"
  config.ssh.insert_key = false

  config.vm.provider "virtualbox" do |vb|
    vb.name = "#{vm_name}"
    #vb.customize ["modifyvm", :id, "--groups", "/Vagrant"]
    vb.memory = "2048"
    vb.cpus = 2
  end
end
