vm_name = "debian-vm01"
vm_net_name = "default"
vm_nic1_ip = "192.168.1.10"

Vagrant.configure("2") do |config|
  config.vm.box = "debian/jessie64"
  config.vm.hostname = "#{vm_name}"
  config.vm.define "#{vm_name}"

  config.ssh.insert_key = false
  config.vm.boot_timeout = 800

  # mkdir -p ./keys/.ssh
  # ssh-keygen -f ./keys/.ssh/vagrant_rsa
  #config.ssh.private_key_path = ["keys/.ssh/vagrant_rsa", "~/.vagrant.d/insecure_private_key"]
  #config.vm.provision "file", source: "keys/.ssh/vagrant_rsa.pub", destination: "~/.ssh/authorized_keys"
  #---
  config.ssh.private_key_path = ["~/.ssh/id_rsa", "~/.vagrant.d/insecure_private_key"]
  config.vm.provision "file", source: "./id_rsa.pub", destination: "~/.ssh/authorized_keys"

  config.vm.synced_folder "srv/", "/srv", type: "rsync"
  config.vm.synced_folder ".", "/vagrant", id: "vagrant-root", disabled: true

  config.vm.network "private_network", ip: "#{vm_nic1_ip}",
    virtualbox__intnet: "#{vm_net_name}"

  config.vm.provider "virtualbox" do |v|
    v.name = "#{vm_name}"
    #vb.customize ["modifyvm", :id, "--groups", "/Vagrant"]
    v.memory = "2048"
    v.customize ["modifyvm", :id, "--vram", "128"]
    v.cpus = 2
  end
end
