Vagrant.configure("2") do |config|
    # Lab name for grouping VM in the VirtualBox
    vm_lab_name = "Lab_Template"
    
    vagrant_files = %w[\
            ../machines/gateway.rb \
            ../machines/srv-vm01.rb
        ]
    
    vagrant_files.each do |vm_file|
        vm = File.expand_path(vm_file, __FILE__)
        eval File.read(vm) if File.exists?(vm)
    end
end