Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  #config.vm.box = "alpine/alpine64"
  #config.vm.box = "debian/jessie64"
  #config.vm.box = "ubuntu/xenial64"
  config.vm.hostname = "ubuntu-vm01"
  config.vm.define "ubuntu-vm01"
  config.ssh.insert_key = false

  config.vm.provider "virtualbox" do |vb|
    vb.name = "ubuntu-vm01"
    #vb.customize ["modifyvm", :id, "--groups", "/Vagrant"]
    vb.memory = "2048"
    vb.cpus = 2
  end
end
