Vagrant.configure("2") do |config|  
  vm_name = "ansible-vm01"
  vm_box = "bento/ubuntu-18.10"

  # VM config
  config.vm.define "#{vm_name}" do |vm_config|
    vm_config.vm.box = "#{vm_box}"
    config.vm.hostname = "#{vm_name}"

    # Network
    config.vm.network "private_network", type: "dhcp",  auto_config: false

    # Provisioners
    # config.vm.provision "shell", path: "provisioners/init.sh"

    config.vm.provision "ansible_local" do |ansible|
      ansible.playbook = "/share/playbooks/01_init.yml"
    end

    # Synced folder
    config.vm.synced_folder "data", "/share/data"
    config.vm.synced_folder "playbooks", "/share/playbooks"
    
    # Virtualbox provider config
    vm_config.vm.provider "virtualbox" do |vb|
      vb.name = "#{vm_name}"
      vb.memory = "1024"
      vb.cpus = 2
    end       
  end
end